"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from accelera.src.automl.wrappers import IQR_transform as IQR_transform
from accelera.src.automl.wrappers import (
    categorical_classification as categorical_classification,
)
from accelera.src.automl.wrappers import (
    categorical_regression as categorical_regression,
)
from accelera.src.automl.wrappers import correlation_graph as correlation_graph
from accelera.src.automl.wrappers import (
    frequency_encoder_transform as frequency_encoder_transform,
)
from accelera.src.automl.wrappers import graph_base as graph_base
from accelera.src.automl.wrappers import (
    numerical_classification as numerical_classification,
)
from accelera.src.automl.wrappers import (
    numerical_regression as numerical_regression,
)
from accelera.src.automl.wrappers import (
    ordinal_classification as ordinal_classification,
)
from accelera.src.automl.wrappers import (
    ordinal_regression as ordinal_regression,
)
from accelera.src.automl.wrappers import (
    preprocessing_report as preprocessing_report,
)
from accelera.src.automl.wrappers import (
    target_classification as target_classification,
)
from accelera.src.automl.wrappers import target_regression as target_regression
from accelera.src.automl.wrappers import text_graph as text_graph
