"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from mainera.src.utils.report_utils.wrappers import (
    display_array_multi_wrapper as display_array_multi_wrapper,
)
from mainera.src.utils.report_utils.wrappers import (
    display_array_single_wrapper as display_array_single_wrapper,
)
from mainera.src.utils.report_utils.wrappers import (
    display_dict_wrapper as display_dict_wrapper,
)
from mainera.src.utils.report_utils.wrappers import (
    display_single_number_wrapper as display_single_number_wrapper,
)
from mainera.src.utils.report_utils.wrappers import (
    display_string_wrapper as display_string_wrapper,
)
from mainera.src.utils.report_utils.wrappers import (
    display_tuple_curve_wrapper as display_tuple_curve_wrapper,
)
from mainera.src.utils.report_utils.wrappers import (
    display_tuple_not_curve_wrapper as display_tuple_not_curve_wrapper,
)
from mainera.src.utils.report_utils.wrappers import (
    metric_display_wrapper as metric_display_wrapper,
)
