"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from accelera.src.accelera_automl.optimization import (
    smac_optimizer as smac_optimizer,
)
