"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from accelera.src.accelera_automl.meta_learning_data import json as json
from accelera.src.accelera_automl.meta_learning_data import (
    json_regression as json_regression,
)
