"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from accelera.src.code_parallelizer import core as core
from accelera.src.code_parallelizer import data as data
from accelera.src.code_parallelizer import db as db
from accelera.src.code_parallelizer import models as models
from accelera.src.code_parallelizer import utils as utils
