"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from accelera.src.code_parallelizer.core import (
    code_optimizer_test as code_optimizer_test,
)
from accelera.src.code_parallelizer.core import (
    code_parallelizer as code_parallelizer,
)
