"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from aistudio.src import core as core
from aistudio.src.version import __version__ as __version__
