"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from mainera.src import core as core
from mainera.src.version import __version__ as __version__
