"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from accelera.src.deployment.tests import conftest as conftest
from accelera.src.deployment.tests import accelera_deployment as accelera_deployment
