"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from accelera.src.accelera_automl.components import classification as classification
from accelera.src.accelera_automl.components import regression as regression
