from __future__ import annotations

import os
import shutil
import sys
from dataclasses import dataclass
from dataclasses import field
from pathlib import Path


def _repo_root_from_this_file() -> Path:
    return Path(__file__).resolve().parents[2]


@dataclass(frozen=True)
class Config:
    REPO_ROOT: Path = _repo_root_from_this_file()
    CACHE_DIR_NAME: str = ".accelera_cache"
    BUILD_DIR_NAME: str = "build"
    BINDINGS_SUBDIR: str = "bindings"
    API_SUBDIR: str = "api"
    PIPELINE_FILENAME: str = "pipeline.pkl"
    DUMMY_PREPROCESSING_OUTPUT_DIR: str = "benchmark_results"
    COMPILE_CACHE_VERSION: str = "preprocess-v2"
    INIT_GENERATOR_SKIP_NAMES: frozenset[str] = frozenset({"__pycache__"})
    INIT_GENERATOR_TEMPLATE_HEADER: str = (
        '"""DO NOT EDIT.\n\n'
        "This file was autogenerated. Do not edit it by hand,\n"
        "since your modifications would be overwritten.\n"
        '"""\n'
    )
    DEPLOYMENT_MODEL_CONFIG: dict[str, object] = field(
        default_factory=lambda: {
            "test_size": 0.2,
            "random_state": 42,
            "cv_folds": 5,
            "model_path": "model.pkl",
            "scaler_path": "scaler.pkl",
            "metadata_path": "model_metadata.json",
        }
    )
    DEPLOYMENT_PARAM_GRID: dict[str, list] = field(
        default_factory=lambda: {
            "n_estimators": [50, 100, 200],
            "max_depth": [None, 10, 20, 30],
            "min_samples_split": [2, 5, 10],
            "min_samples_leaf": [1, 2, 4],
            "max_features": ["sqrt", "log2"],
            "bootstrap": [True, False],
        }
    )
    DATASETS: dict[str, dict] = field(
        default_factory=lambda: {
            "customer_purchase_data": {
                "id": "1OCe4X8mVFEwWz0cfQyAJKNiZMbiUGbB2",
                "metadata": {},
            },
            "TestReviews": {
                "id": "1pBNGL9NuScgUb16Yh8W6gFzhXanCWa9q",
                "metadata": {},
            },
            "Dataset_spine": {
                "id": "1RmaNadcroXrqodMq1APBQBhIKBIZLbvJ",
                "metadata": {},
            },
            "DailyDialog": {
                "id": "1oWgWAZpvVAgnxK3P-0sqElWDWMozdK4P",
                "metadata": {},
            },
            "job_salary_prediction_dataset": {
                "id": "1r5HEDyelbzfZbXPSx-0G7vEvrgXGqb9r",
                "metadata": {},
            },
            "Housing": {
                "id": "1VMtLcWDcigwkimpf-eWVMZ7zJMUf7wxs",
                "metadata": {},
            },
            "student_placement_synthetic": {
                "id": "1l3YRaiPNA4EowBFuj6cm0v4yS2DQOY1M",
                "metadata": {},
            },
            "Titanic-Dataset": {
                "id": "1VWRzvPDcFOo7YByJtKKupH3H0czFAHCx",
                "metadata": {},
            },
            "heart": {
                "id": "1HG9BPIS-PFHzzXBnKrohMCrmr7W9oxJY",
                "metadata": {},
            },
            "student_exam_performance_dataset": {
                "id": "19mH4wgsK2-zcttdTFl6jk_BR83lrKIS7",
                "metadata": {},
            },
            "diabetes_dataset": {
                "id": "1n0lDQbi662-Kabrq5KJrjs2_uFQ1hBpS",
                "metadata": {},
            },
        }
    )

    DEFAULT_CLANG_ARGS: tuple[str, ...] = ("-std=c++17",)
    CLANG_FORMAT_BIN: str = os.getenv("ACCELERA_CLANG_FORMAT_BIN", "clang-format")
    ENABLE_CPP_FORMATTING: bool = (
        os.getenv("ACCELERA_ENABLE_CPP_FORMATTING", "1") == "1"
    )

    CLASSIFIER_ENDPOINT: str = os.getenv(
        "ACCELERA_CLASSIFIER_ENDPOINT",
        "https://accelera-ai-open-mp-classifier.hf.space/predict",
    )
    DATASET_DRIVE_FOLDER_ENDPOINT: str = (
        "https://drive.google.com/drive/folders/1ijBkIdvLnVGbINjDklTsC3-z3jc-_GIE"
    )
    REQUEST_TIMEOUT_S: int = int(os.getenv("ACCELERA_REQUEST_TIMEOUT_S", "10"))

    # If 1, `accelera/__init__.py` will
    # raise if optional `accelera.api` import fails.
    STRICT_API_IMPORT: bool = os.getenv("ACCELERA_STRICT_API_IMPORT", "0") == "1"

    @property
    def cache_dir(self) -> Path:
        return self.REPO_ROOT / self.CACHE_DIR_NAME

    @property
    def bindings_dir(self) -> Path:
        return self.REPO_ROOT / self.BUILD_DIR_NAME / self.BINDINGS_SUBDIR

    @property
    def api_dir(self) -> Path:
        return self.REPO_ROOT / "accelera" / self.API_SUBDIR

    @property
    def deployment_root(self) -> Path:
        cwd = Path(os.getcwd()).resolve()
        for p in [cwd] + list(cwd.parents):
            if p.name == ".accelera_deployment":
                return p
        for p in [cwd] + list(cwd.parents):
            if (p / ".accelera_deployment").is_dir():
                return p / ".accelera_deployment"
        return cwd / ".accelera_deployment"

    @property
    def deployment_experiments_dir(self) -> Path:
        return self.deployment_root / "experiments"

    @property
    def deployment_models_dir(self) -> Path:
        return self.deployment_root / "models"

    @property
    def deployment_config_file(self) -> Path:
        return self.deployment_root / "config.json"

    @property
    def deployment_index_file(self) -> Path:
        return self.deployment_experiments_dir / "experiments.json"

    def ensure_bindings_on_syspath(self) -> None:
        bindings = str(self.bindings_dir)
        if bindings not in sys.path:
            sys.path.insert(0, bindings)

    def ensure_graphviz_on_path(self) -> None:
        if dot := shutil.which("dot"):
            dot_dir = Path(dot).parent
            if hasattr(os, "add_dll_directory"):
                os.add_dll_directory(str(dot_dir))
            return

        if os.name != "nt":
            return

        candidates = [
            Path(os.getenv("ProgramFiles", "")) / "Graphviz" / "bin",
            Path(os.getenv("ProgramFiles(x86)", "")) / "Graphviz" / "bin",
            Path(os.getenv("LOCALAPPDATA", "")) / "Programs" / "Graphviz" / "bin",
        ]

        for candidate in candidates:
            if (candidate / "dot.exe").exists():
                os.environ["PATH"] = (
                    f"{candidate}{os.pathsep}{os.environ.get('PATH', '')}"
                )
                if hasattr(os, "add_dll_directory"):
                    os.add_dll_directory(str(candidate))
                return

    def ensure_llvm_on_path(self) -> None:
        if clangxx := shutil.which("clang++"):
            clang_dir = Path(clangxx).parent
            if hasattr(os, "add_dll_directory"):
                os.add_dll_directory(str(clang_dir))
            return

        if os.name != "nt":
            return

        candidates = [
            self.REPO_ROOT
            / self.BUILD_DIR_NAME
            / "_deps"
            / "llvm-18.1.8-windows"
            / "clang+llvm-18.1.8-x86_64-pc-windows-msvc"
            / "bin",
            Path(os.getenv("ProgramFiles", "")) / "LLVM" / "bin",
            Path(os.getenv("ProgramFiles(x86)", "")) / "LLVM" / "bin",
            Path(os.getenv("LOCALAPPDATA", "")) / "Programs" / "LLVM" / "bin",
        ]

        for candidate in candidates:
            if (candidate / "clang++.exe").exists():
                os.environ["PATH"] = (
                    f"{candidate}{os.pathsep}{os.environ.get('PATH', '')}"
                )
                if hasattr(os, "add_dll_directory"):
                    os.add_dll_directory(str(candidate))
                return


config = Config()
